server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.139.com
    username: xx@139.com
    password: xx
    test-connection: false
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactor
jusic:
  music-expire-time: 1200000
  retry-count: 1
  vote-rate: 0.3
  default-music-file: 'classpath:music/default-list.txt'#'file:/usr/local/nginx/html/default-list.txt' # #
  wy-top-url: 'https://music.163.com/discover/toplist?id=3778678'
  music-json: 'classpath:lizhimusic.json'#'file:/usr/local/nginx/html/lizhimusic.json' #json格式歌曲列表（for禁歌） # #
  music-serve-domain: 'http://localhost:8888'
  music-serve-domain-qq: 'http://localhost:3300'
  music-serve-domain-mg: 'http://localhost:3400'#'http://localhost:3400'#
  mail-send-from: 'xx@139.com'
  mail-send-to: 'xx@qq.com'
  serverJUrl: 'https://sc.ftqq.com/xx.send'



